version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "cargo"
    directory: "/lib/v4lise"
    schedule:
      interval: "monthly"
