[package]
name = "dradis"
version = "0.4.4"
authors = ["Maxime Ripard <maxime@cerno.tech>"]
edition = "2021"
description = "HDMI Test Application"
license-file = "LICENSE"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
panic = "abort"

[build-dependencies]
built = { version = "0.7.7", features = ["git2"] }

[dependencies]
anyhow = "1.0.97"
bitflags = "2.9.0"
byteorder = "1.5.0"
chrono = "0.4.40"
clap = { version = "4.5.32", features = ["cargo", "derive"] }
dma-buf = "0.4.0"
dma-heap = "0.4.0"
image = { version = "0.25.5", default-features = false }
libc = "0.2.171"
log = "0.4.26"
nix = { version = "0.29.0", features = ["ioctl"] }
num-traits = "0.2.19"
redid = { git = "https://github.com/mripard/redid.git" }
rqrr = "0.9.0, <0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_with = "3.12.0"
serde_yaml = "0.9.34"
simplelog = "0.12.2"
thiserror = "2.0.12"
twox-hash = "2.1.0"

[dependencies.v4lise]
path = "lib/v4lise"

[package.metadata.deb]
section = "utility"
priority = "optional"
assets = [
	["target/release/dradis", "usr/bin/", "755"],
	["samples/test-single-mode-720p.yaml", "usr/share/dradis/samples/", "644"],
]

[package.metadata.deb.variants.rpi4]
name = "dradis-raspberrypi4"
