[package]
name = "test-capture"
version = "0.1.0"
authors = ["Maxime Ripard <maxime@cerno.tech>"]
edition = "2018"

[dependencies]
libc = "0.2"
mmap = "^0.1"
twox-hash = "1.5"

[dependencies.v4lise]
path = "lib/v4lise"

[build-dependencies]
bindgen = "0.53"