[package]
name = "dradis"
version = "0.1.0"
authors = ["Maxime Ripard <maxime@cerno.tech>"]
edition = "2021"

[dependencies]
byteorder = "1.3.0"
clap = "4.0.30"
dma-buf = "0.3.0"
dma-heap = "0.2.1"
edid = { git = "https://github.com/mripard/edid-rs.git" }
libc = "0.2.0"
log = "0.4.0"
serde = { version = "1.0.0", features = ["derive"] }
serde_yaml = "0.9.14"
simplelog = "0.12.0"
strum = "0.24.1"
strum_macros = "0.24.3"
twox-hash = "1.5.0"

[dependencies.v4lise]
path = "lib/v4lise"
