[package]
name = "dradis"
version = "0.2.0"
authors = ["Maxime Ripard <maxime@cerno.tech>"]
edition = "2021"
license-file = "LICENSE"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
panic = "abort"

[dependencies]
anyhow = "1.0.68"
byteorder = "1.4.3"
clap = "4.0.32"
dma-buf = "0.3.0"
dma-heap = "0.2.1"
edid = { git = "https://github.com/mripard/edid-rs.git" }
image = { version = "0.24.5", default-features = false }
libc = "0.2.139"
log = "0.4.17"
rqrr = "0.6.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
serde_with = "2.1.0"
serde_yaml = "0.9.16"
simplelog = "0.12.0"
thiserror = "1.0.38"
twox-hash = "1.6.3"

[dependencies.v4lise]
path = "lib/v4lise"
