[package]
name = "dradis"
version = "0.3.4"
authors = ["Maxime Ripard <maxime@cerno.tech>"]
edition = "2021"
description = "HDMI Test Application"
license-file = "LICENSE"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
panic = "abort"

[build-dependencies]
built = { version = "0.7.1", features = ["git2"] }

[dependencies]
anyhow = "1.0.81"
byteorder = "1.5.0"
clap = { version = "4.5.4", features = ["cargo", "derive"] }
dma-buf = "0.4.0"
dma-heap = "0.4.0"
image = { version = "0.25.1", default-features = false }
libc = "0.2.153"
log = "0.4.21"
nix = { version = "0.28.0", features = ["ioctl"] }
num-traits = "0.2.18"
redid = { path = "../redid" }
rqrr = "0.7.1"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
serde_with = "3.7.0"
serde_yaml = "0.9.34"
simplelog = "0.12.2"
thiserror = "1.0.58"
twox-hash = "1.6.3"
v4l2r = "0.0.1"

[package.metadata.deb]
section = "utility"
priority = "optional"
assets = [
	["target/release/dradis", "usr/bin/", "755"],
	["samples/test-single-mode-720p.yaml", "usr/share/dradis/samples/", "644"],
]

# It's a bit of a hack, but we can't run cargo deb within cross until cross
# allows us to:
# https://github.com/cross-rs/cross/issues/716
#
# Since we're not running it within the container, the host libraries are used
# by cargo-deb and it will pick the host C library as a dependency, even though
# it might have been built with something else entirely.
#
# Let's force the current container C library version.
depends = "libc6:arm64 (>= 2.17)"
