[package]
name = "dradis"
version = "0.1.0"
authors = ["Maxime Ripard <maxime@cerno.tech>"]
edition = "2021"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
panic = "abort"

[dependencies]
byteorder = "1.3.0"
clap = "2.33.0"
dma-buf = "0.3.0"
dma-heap = "0.2.1"
edid = { git = "https://github.com/mripard/edid-rs.git" }
image = "0.24.5"
libc = "0.2.0"
log = "0.4.0"
rqrr = "0.5.2"
serde = { version = "1.0.0", features = ["derive"] }
serde_json = "1.0.89"
serde_with = "2.1.0"
serde_yaml = "0.9.14"
simplelog = "0.12.0"
thiserror = "1.0.38"
twox-hash = "1.5.0"

[dependencies.v4lise]
path = "lib/v4lise"
