[package]
name = "test-capture"
version = "0.1.0"
authors = ["Maxime Ripard <maxime@cerno.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2"
glob = "0.3"
libc = "0.2"
memmap = "0.7"
twox-hash = "1.5"
