[package]
name = "dradis"
version = "0.1.0"
authors = ["Maxime Ripard <maxime@cerno.tech>"]
edition = "2021"

[dependencies]
byteorder = "1.3.0"
clap = "2.33.0"
dma-buf = { git = "https://github.com/mripard/dma-buf.git" }
dma-heap = { git = "https://github.com/mripard/dma-heap.git" }
edid = { git = "https://github.com/mripard/edid-rs.git" }
libc = "0.2.0"
log = "0.4.0"
serde = { version = "1.0.0", features = ["derive"] }
serde_yaml = "0.8.0"
simplelog = "0.10.0"
twox-hash = "1.5.0"

[dependencies.v4lise]
path = "lib/v4lise"
