[package]
name = "linux-raw"
authors.workspace = true
edition.workspace = true
license-file.workspace = true
publish = false
repository.workspace = true
version.workspace = true

[dependencies]

[lints]
workspace = true
