name: Release

on:
  push:
    tags:
      - 'v**'

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      # We need to mangle with the target features because rustc (llvm,
      # actually) will enable optional CPU features that aren't found on the
      # Pi4's CPU.
      #
      # See https://github.com/rust-lang/rust/issues/125033
      RUSTFLAGS: -C target-cpu=cortex-a72 -C target_feature=-aes -C target_feature=-sha2

    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            target: aarch64-unknown-linux-gnu
            override: true

      - name: Build Cargo Config
        run: |
          echo -e "[target.aarch64-unknown-linux-gnu]\nlinker = \"aarch64-linux-gnu-ld\"\nstrip = { path = \"aarch64-linux-gnu-strip\" }" > ~/.cargo/config

      - name: Install cargo-deb
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-deb
          version: latest

      - name: Install cross
        uses: actions-rs/install@v0.1
        with:
          crate: cross
          version: latest

      - uses: actions/checkout@v2

      - name: Build the Package
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=aarch64-unknown-linux-gnu

      - name: Build Debian Package
        run: |
          cargo deb --no-build --target=aarch64-unknown-linux-gnu -o dradis-aarch64-raspberrypi-4.deb

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "target/aarch64-unknown-linux-gnu/debian/dradis_*.deb"
