name: Dradis Release

on:
  push:
    tags:
      - 'dradis-v**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build_deb_pkg_release:
    name: Build Release Debian Package
    uses: ./.github/workflows/deb_pkg.yml
    with:
      distribution-version: bookworm

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [ build_deb_pkg_release ]

    steps:
      - name: Download Debian Packet Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build_deb_pkg_release.outputs.artifact_name }}

      - uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ needs.build_deb_pkg_release.outputs.artifact_name }}
